// BookstoreViewModel.idl
import "BookSku.idl";

namespace Bookstore
{
	runtimeclass BookstoreViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		String Title;
		BookSku BookSku;
		Windows.Foundation.Collections.IObservableVector<IInspectable> BookSkus{ get; };
	}
}